# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paicore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'paicore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpaicore.proto\x12\x07paicore\" \n\x0bInitRequest\x12\x11\n\tthread_id\x18\x01 \x01(\r\"B\n\x0cInferRequest\x12\x11\n\tthread_id\x18\x01 \x01(\r\x12\x11\n\ttimesteps\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"$\n\rConfigRequest\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\r\"\"\n\x0bTestRequest\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\r\"\xc6\x01\n\x0bHostMessage\x12(\n\x08init_req\x18\x01 \x01(\x0b\x32\x14.paicore.InitRequestH\x00\x12*\n\tinfer_req\x18\x02 \x01(\x0b\x32\x15.paicore.InferRequestH\x00\x12,\n\nconfig_req\x18\x03 \x01(\x0b\x32\x16.paicore.ConfigRequestH\x00\x12(\n\x08test_req\x18\x04 \x01(\x0b\x32\x14.paicore.TestRequestH\x00\x42\t\n\x07payload\"2\n\x0cInitResponse\x12\x11\n\tthread_id\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\"Q\n\rInferResponse\x12\x11\n\tthread_id\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0e\n\x06\x63ycles\x18\x04 \x01(\r\"6\n\x0e\x43onfigResponse\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\"L\n\x0cTestResponse\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0emismatch_frame\x18\x03 \x01(\r\"\xd0\x01\n\rDeviceMessage\x12*\n\tinit_resp\x18\x01 \x01(\x0b\x32\x15.paicore.InitResponseH\x00\x12,\n\ninfer_resp\x18\x02 \x01(\x0b\x32\x16.paicore.InferResponseH\x00\x12.\n\x0b\x63onfig_resp\x18\x03 \x01(\x0b\x32\x17.paicore.ConfigResponseH\x00\x12*\n\ttest_resp\x18\x04 \x01(\x0b\x32\x15.paicore.TestResponseH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paicore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=26
  _globals['_INITREQUEST']._serialized_end=58
  _globals['_INFERREQUEST']._serialized_start=60
  _globals['_INFERREQUEST']._serialized_end=126
  _globals['_CONFIGREQUEST']._serialized_start=128
  _globals['_CONFIGREQUEST']._serialized_end=164
  _globals['_TESTREQUEST']._serialized_start=166
  _globals['_TESTREQUEST']._serialized_end=200
  _globals['_HOSTMESSAGE']._serialized_start=203
  _globals['_HOSTMESSAGE']._serialized_end=401
  _globals['_INITRESPONSE']._serialized_start=403
  _globals['_INITRESPONSE']._serialized_end=453
  _globals['_INFERRESPONSE']._serialized_start=455
  _globals['_INFERRESPONSE']._serialized_end=536
  _globals['_CONFIGRESPONSE']._serialized_start=538
  _globals['_CONFIGRESPONSE']._serialized_end=592
  _globals['_TESTRESPONSE']._serialized_start=594
  _globals['_TESTRESPONSE']._serialized_end=670
  _globals['_DEVICEMESSAGE']._serialized_start=673
  _globals['_DEVICEMESSAGE']._serialized_end=881
# @@protoc_insertion_point(module_scope)
